import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "LinkOSM ",
  description: "Generated by Create Next App",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      className="bg-gray-100 text-white-900 dark:bg-gray-900">
      <header
      className="bg-blue-300 shadow-sm py-4">
        <h1>Header</h1>
      </header>
        {children}
        <footer
        className="bg-blue-300 shadow-sm py-4">
         <h3>Footer</h3>
        </footer>
      </body>
    </html>
  );
}
